### ISSUE TITLE
Getting random errors while running the program!!

### ISSUE THREAD

**Issue by cyblogerz** [cyblogerz/Hospital-Management-software#1]
### Hello, I am a beginner at Python , and i am trying to develop a program  ,but i am getting errors while running it. Please help me in fixing  it .

**Comment by vmdhhh** [comment]
Interested. Please let me know the details

**Comment by cyblogerz** [comment]
@vmdhhh  this issue has been resolved , but there are other issues that i cant resolve as I am just a beginner please check those if you are interested
