### ISSUE TITLE
Running into error while trying to search in the database

### ISSUE THREAD

**Issue by cyblogerz** [cyblogerz/Hospital-Management-software#6]
![Screenshot from 2020-12-19 20-23-45](https://user-images.githubusercontent.com/74711322/102693852-8a920700-4243-11eb-98d7-60989c6d7d87.png)

**Comment by Sumit112192** [comment]
One issue which I found was that while providing arguments to sql statements and if the argument is only one provide it in the form of tuple.
For eg
c.execute("SELECT * FROM store WHERE name = (?)", name)        {You have wrote like this}
c.execute("SELECT * FROM store WHERE name = (?)", (name,))     {Instead write like this}

Now also you were using Medicine class (which you have created in funcs.py) in the database.py so thats another error.
And in the github home page of this repo you have uploaded HMS.db in the top level folder whereas it should be in Main folder.
If you have any doubt ask me freely.
