### ISSUE TITLE
Merging Duplicate medicines in the  database

### ISSUE THREAD

**Issue by cyblogerz** [cyblogerz/Hospital-Management-software#8]
![Screenshot from 2020-12-19 21-56-26](https://user-images.githubusercontent.com/74711322/102694124-16586300-4245-11eb-935d-695b86861c29.png)

**Comment by Sumit112192** [comment]
Why do you want to merge the medicines. As it can be seen from the screenshot, the medicines are of different variants both are having different Price and also different ExpiryDate.
Also maybe while inputing only you can check in the database if such medicine exists.
